### ISSUE TITLE
Sandbox/Dev: Error on batch ingest

### ISSUE THREAD

**Issue by calhist** [calhist/dam_workflow_scripts#16]
In the new sandbox/dev environment, I'm getting an error when I try to do a batch ingest of a ZIP containing TIF and XML:

![image](https://cloud.githubusercontent.com/assets/25800148/24274689/21dce17c-0fe7-11e7-9267-cd216cc2ddd3.png)

**Comment by laddhanson** [comment]
@calhist, batches should be working now.
