### ISSUE TITLE
Create islandora sandbox

### ISSUE THREAD

**Issue by laddhanson** [calhist/dam_workflow_scripts#9]
- [x] create default Ubuntu 14.04 image (include postfix and hardening)
- [x] create Apache 2.4 image
- [x] create PHP 5.6 image
- [x] test MySQL 5.5 configuration
- [x] create Drupal 7 image
- [x] test Tomcat 7 configuration (with Java 8)
- [x] test Solr 4.2 configuration
- [x] test Fedora 3.8 configuration
- [x] test GSearch 2.7 configuration (including DGI extensions)
- [x] test ffmpeg configuration
- [x] create Islandora 7.x-1.8 image
- [x] create islandora-chs.laddhanson.org stack

**Comment by laddhanson** [comment]
~~upgrade to Ubuntu 16.04~~
~~upgrade Apache 2.4~~
~~upgrade MySQL~~
upgrade Drupal 7
upgrade Tomcat 7
upgrade Solr 4.2
upgrade Fedora 3.8
upgrade GSearch 2.7
upgrade ffmpeg
upgrade Islandora 7.x-1.8

**Comment by calhist** [comment]
Awesome! Glad to see this happened so quickly!
When do you think we might have access to it?
Thanks!
